
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brian
 */
public class GUIAsesorComercial extends javax.swing.JFrame {
    AsesorComercial as1 = new AsesorComercial("Thomas","Wayne","0987654234","02228899","thomas.wayne@hotmail.com");
    AsesorComercial as2 = new AsesorComercial("Ricardo","Tapia","0987654233","02227899","ricardo.tapia@hotmail.com");
    AsesorComercial as3 = new AsesorComercial("Barbara","Gordon","0987654234","02228899","barbara.gordon@hotmail.com");
    
    ArrayList<AsesorComercial> asesores = new ArrayList<>();
    /**
     * Creates new form GUIAsesorComercial
     */
    public GUIAsesorComercial() {
        initComponents();
        asesores.add(as1);
        asesores.add(as2);
        asesores.add(as3);
        double n = Math.random()*12;
        if(n<4){
            txaAsesores.setText("Gracias por elegir nuestros servicios, a continuación los datos de uno de nuestros Asesores disponibles: "
                    +"\n"+"\n"+"Nombre: "+asesores.get(0).getNombre()+"\n"+"\n"+"Apellido: "+asesores.get(0).getApellido()+"\n"+"\n"+
                    "Número de Celular: "+asesores.get(0).getNumCelular()+"\n"+"\n"+"Número de telefono: "+asesores.get(0).getNumTelefono()+
                    "\n"+"\n"+"Mail: "+asesores.get(0).getCorreo());
        }
        if(n>4 && n<=8){
            txaAsesores.setText("Gracias por elegir nuestros servicios, a continuación los datos de uno de nuestros Asesores disponibles: "
                    +"\n"+"\n"+"Nombre: "+asesores.get(1).getNombre()+"\n"+"\n"+"Apellido: "+asesores.get(1).getApellido()+"\n"+"\n"+
                    "Número de Celular: "+asesores.get(1).getNumCelular()+"\n"+"\n"+"Número de telefono: "+asesores.get(1).getNumTelefono()+
                    "\n"+"\n"+"Mail: "+asesores.get(1).getCorreo());
        }
        if(n>8 && n<12){
            txaAsesores.setText("Gracias por elegir nuestros servicios, a continuación los datos de uno de nuestros Asesores disponibles"
                    +"\n"+"\n"+"Nombre: "+asesores.get(2).getNombre()+"\n"+"\n"+"Apellido: "+asesores.get(2).getApellido()+"\n"+"\n"+
                    "Número de Celular: "+asesores.get(2).getNumCelular()+"\n"+"\n"+"Número de telefono: "+asesores.get(2).getNumTelefono()+
                    "\n"+"\n"+"Mail: "+asesores.get(2).getCorreo());
        }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAsesor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAsesores = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        pnlAsesor.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Asesor Comercial"));

        txaAsesores.setEditable(false);
        txaAsesores.setColumns(20);
        txaAsesores.setRows(5);
        jScrollPane1.setViewportView(txaAsesores);

        javax.swing.GroupLayout pnlAsesorLayout = new javax.swing.GroupLayout(pnlAsesor);
        pnlAsesor.setLayout(pnlAsesorLayout);
        pnlAsesorLayout.setHorizontalGroup(
            pnlAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsesorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAsesorLayout.setVerticalGroup(
            pnlAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsesorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAsesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAsesorComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAsesorComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAsesorComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAsesorComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAsesorComercial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAsesor;
    private javax.swing.JTextArea txaAsesores;
    // End of variables declaration//GEN-END:variables
}
